name: "godot"

env:
  GODOT_VERSION: 4.1.1

on:
  push:
    branches: [ main ]

  workflow_dispatch:

jobs:
  export:
    name: Export Topster Manager
    runs-on: ubuntu-latest
    container:
      image: barichello/godot-ci:4.1.1

    steps:
      - name: checkout
        uses: actions/checkout@v2

      - name: setup
        run: |
          mkdir -v -p ~/.local/share/godot/templates
          mv /root/.local/share/godot/templates/${GODOT_VERSION}.stable ~/.local/share/godot/templates/${GODOT_VERSION}.stable

      - name: build
          cd topster-manager
          mkdir -v -p build/web
          godot -v --export "HTML5" ./build/web/index.html

      - name: rsync
        run: |
          apt-get update && apt-get install -y rsync

      - name: deploy
        uses: JamesIves/github-pages-deploy-action@releases/v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: pages
          FOLDER: build/web
